name: 'Build and push to GCR'
description: 'Build and push to GCR'

inputs:
  # Ref: https://github.com/RafikFarhad/push-to-gcr-github-action/blob/master/action.yaml
  gcloud_service_key:
    description: Google cloud service key json file as plain text or base64 encrypted
    required: true
  registry:
    description: The registry where the image should be pushed
    required: true
  project_id:
    description: The project id
    required: true
  image_name:
    description: The image name
    required: true
  dockerfile:
    description: Dockerfile that will build the image
    required: false
    default: ""
  context:
    description: Docker build context
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - id: commit
      name: output commit hash
      uses: pr-mpt/actions-commit-hash@v1
    - id: tag_name
      name: replace slash to dash
      uses: mad9000/actions-find-and-replace-string@1
      with:
        source: ${{ format('{0}-{1}', github.ref_name, steps.commit.outputs.short) }}
        find: '/'
        replace: '-'
    - name: Build and push Docker image with auto tagging
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ inputs.gcloud_service_key }}
        registry: ${{ inputs.registry }}
        project_id: ${{ inputs.project_id }}
        image_name: ${{ inputs.image_name }}
        image_tag: latest,${{ steps.tag_name.outputs.value }}
        dockerfile: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
