name: 'Build and push to GCR'
description: 'Build and push to GCR'

inputs:
  gcloud_service_key:
    description: json
    required: true
  registry:
    description: The registry where the image should be pushed
    required: true
  project_id:
    description: The project id
    required: true
  image_name:
    description: The image name
    required: true
  dockerfile:
    description: Dockerfile that will build the image
    required: false
    default: ""
  context:
    description: Docker build context
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - id: commit
      name: Output commit hash
      uses: pr-mpt/actions-commit-hash@v2

    - id: tag_name
      name: Replace slash to dash
      uses: mad9000/actions-find-and-replace-string@2
      with:
        source: ${{ format('{0}-{1}', github.ref_name, steps.commit.outputs.short) }}
        find: '/'
        replace: '-'

#    - id: image_name
#      shell: bash
#      run: echo value=${{ inputs.registry }}/${{ inputs.project_id }}/${{ inputs.image_name }} >> $GITHUB_OUTPUT

    - name: Build a docker image
      shell: bash
      run: docker build \
        -t ${IMAGE}:latest \
        -t ${IMAGE}:${{ steps.tag_name.outputs.value }} \
        -f ${{ inputs.dockerfile }} .
      env:
        IMAGE: ${{ inputs.registry }}/${{ inputs.project_id }}/${{ inputs.image_name }}
      working-directory: ${{ inputs.context }}

#    - id: 'auth'
#      uses: 'google-github-actions/auth@v0'
#      with:
#        credentials_json: '${{ inputs.gcloud_service_key }}'
#
#    - name: 'Set up Cloud SDK'
#      uses: 'google-github-actions/setup-gcloud@v0'
#
#    - name: Configure docker
#      shell: bash
#      run: gcloud auth configure-docker --quiet
#
#    - name: Push the docker image
#      shell: bash
#      run: docker push asia.gcr.io/${{ inputs.project_id }}/sueken:${GITHUB_SHA::7}
