name: 'Build and push to GCR'
description: 'Build and push to GCR'

inputs:
  gcloud_service_key:
    description: json
    required: true
  registry:
    description: The registry where the image should be pushed
    required: true
  project_id:
    description: The project id
    required: true
  image_name:
    description: The image name
    required: true
  dockerfile:
    description: Dockerfile that will build the image
    required: false
    default: ""
  context:
    description: Docker build context
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - id: commit
      name: output commit hash
      uses: pr-mpt/actions-commit-hash@v1

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ inputs.gcloud_service_key }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Use gcloud CLI
      shell: bash
      run: gcloud auth configure-docker --quiet

    - id: tag_name
      name: replace slash to dash
      uses: mad9000/actions-find-and-replace-string@1
      with:
        source: ${{ format('{0}-{1}', github.ref_name, steps.commit.outputs.short) }}
        find: '/'
        replace: '-'

#    - name: Build and push Docker image with auto tagging
#      uses: RafikFarhad/push-to-gcr-github-action@v4.1
#      with:
#        gcloud_service_key: ${{ inputs.gcloud_service_key }}
#        registry: ${{ inputs.registry }}
#        project_id: ${{ inputs.project_id }}
#        image_name: ${{ inputs.image_name }}
#        image_tag: latest,${{ steps.tag_name.outputs.value }}
#        dockerfile: ${{ inputs.dockerfile }}
#        context: ${{ inputs.context }}
#