name: release

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run gcr-docker-action
        uses: 00ken00/gcr-docker-action@main
        with:
          gcloud_service_key: ${{ secrets.GCP_CREDENTIALS }}
          registry: asia.gcr.io
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          image_name: gcr-docker-action
          dockerfile: Dockerfile.ci
          context: .github/workflows/

